# Generated by Django 4.1.7 on 2023-09-05 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sentimen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('neg', models.CharField(max_length=255)),
                ('neu', models.CharField(max_length=255)),
                ('pos', models.CharField(max_length=255)),
                ('compound', models.CharField(max_length=255)),
            ],
        ),
    ]
